# Generated by Django 2.1.7 on 2019-02-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_sliderimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SliderImages',
            new_name='SliderImage',
        ),
    ]
