# Generated by Django 2.1.7 on 2019-02-22 17:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190222_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 22, 17, 2, 18, 243587, tzinfo=utc)),
        ),
    ]
